#!/bin/bash -i

set -xe

export POETRY_VIRTUALENVS_IN_PROJECT=true
cd "$(dirname "$0")"
source lib.sh
cd ..

make install

if [ ! -z "$ATUIN_LOGIN" ]
then
    echo $ATUIN_LOGIN | bash -i
    atuin sync -f
fi

~/.emacs.d/bin/doom sync
