#!/bin/bash

set -xe

cd "$(dirname "$0")"
source lib.sh
cd ..

# secrets are available only here
# GITHUB_TOKEN everywhere
if [ ! -z "$ATUIN_LOGIN" ]
then
    echo $ATUIN_LOGIN | bash -i
    atuin sync -f
fi

# again because the hostname has changed
~/.emacs.d/bin/doom sync --force
